### PR TITLE
Fix linear-gradient direction conversion for legacy vendor-prefixed values

### LINKED ISSUE #918: linear-gradient `to` keyword conversion error
## input

```css
.foo {
    background: linear-gradient(to right, red, green);
}
```

## output

[playground](https://lightningcss.dev/playground/index.html#%7B%22minify%22%3Afalse%2C%22customMedia%22%3Afalse%2C%22cssModules%22%3Afalse%2C%22analyzeDependencies%22%3Afalse%2C%22targets%22%3A%7B%22chrome%22%3A1441792%7D%2C%22include%22%3A0%2C%22exclude%22%3A0%2C%22source%22%3A%22.foo%20%7B%5Cn%20%20%20%20background%3A%20linear-gradient(to%20right%2C%20red%2C%20green)%3B%5Cn%7D%5Cn%5Cn.bar%20%7B%5Cn%20%20background%3A%20linear-gradient(to%20top%20right%2C%20red%2C%20green)%3B%5Cn%7D%22%2C%22visitorEnabled%22%3Afalse%2C%22visitor%22%3A%22%7B%5Cn%20%20Color(color)%20%7B%5Cn%20%20%20%20if%20(color.type%20%3D%3D%3D%20'rgb')%20%7B%5Cn%20%20%20%20%20%20color.g%20%3D%200%3B%5Cn%20%20%20%20%20%20return%20color%3B%5Cn%20%20%20%20%7D%5Cn%20%20%7D%5Cn%7D%22%2C%22unusedSymbols%22%3A%5B%5D%2C%22version%22%3A%22local%22%7D)

```css
.foo {
  background: -webkit-linear-gradient(right, red, green); /* The directions of the old and new grammars are not equivalent. */
  background: linear-gradient(to right, red, green);
}
```

## expected

```css
.foo {
  background: -webkit-linear-gradient(left, red, green);
  background: linear-gradient(to right, red, green);
}
```

https://developer.mozilla.org/en-US/docs/Web/CSS/gradient/linear-gradient#browser_compatibility

Image

### PR DESCRIPTION
**Pull request by lucasweng**
- Fixes #918
- Ports angle conversion from [Autoprefixer’s implementation](https://github.com/postcss/autoprefixer/blob/541295c0e6dd348db2d3f52772b59cd403c59d29/lib/hacks/gradient.js#L103-L112). See this [comment](https://github.com/parcel-bundler/lightningcss/pull/936#discussion_r2039654448) for a more detailed comparison.

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -13282,7 +13282,7 @@ mod tests {
       ".foo { background: linear-gradient(lch(56.208% 136.76 46.312), lch(51% 135.366 301.364)) }",
       indoc! { r#"
         .foo {
-          background: -webkit-linear-gradient(#ff0f0e, #7773ff);
+          background: -webkit-linear-gradient(top, #ff0f0e, #7773ff);
```
Comment (lucasweng) [inline src/lib.rs:13285]: Some test results include an extra `top` keyword in vendor-prefixed linear-gradient values because the original input omits the direction. When unspecified, the new syntax defaults to `to bottom`, which is converted to `top` in legacy syntax.

**Comment by yisibl** [comment]
There are more test cases in Autoprefixer, and I think it would be nice to be able to synchronize them here for testing.

File: src/values/gradient.rs [hunk 2]
```diff
@@ -530,6 +540,52 @@ impl LineDirection {
...
+    LineDirection::Angle(angle) => {
+      let angle = angle.clone();
+      match angle {
+        Angle::Deg(number) => {
+          // Add 90 degrees
+          let number = (450.0 - number).abs() % 360.0;
+          // Round the number to 3 decimal places
+          let number = (number * 1000.0).round() / 1000.0;
+          LineDirection::Angle(Angle::Deg(number))
+        }
```
Comment (lucasweng) [inline src/values/gradient.rs:582]: This conversion is ported from [Autoprefixer’s implementation](https://github.com/postcss/autoprefixer/blob/main/lib/hacks/gradient.js#L103-L112)

File: src/lib.rs [hunk 3]
```diff
@@ -13042,7 +13042,7 @@ mod tests {
       indoc! {r#"
       .foo {
         background-image: -webkit-gradient(linear, 0 0, 100% 0, from(red), to(#00f));
-        background-image: -webkit-linear-gradient(90deg, red, #00f);
+        background-image: -webkit-linear-gradient(0deg, red, #00f);
```
Comment (lucasweng) [inline src/lib.rs:13045]: The new angle conversion works quite well. Take these test cases for example:

<details>
  <summary><code>background-image: linear-gradient(90deg, red, blue);</code></summary>

  test

  - Before (angle unchanged): `-webkit-linear-gradient(90deg, red, #00f);`
before

  - After `background-image: -webkit-linear-gradient(0deg, red, #00f);`
Screenshot 2025-04-11 at 22 19 06
</details>

<details>
  <summary>
    <code>background: linear-gradient(350.5deg, white, black)</code>
     from the first test case ported from Autoprefixer
  </summary>

  test2


  - Before (angle unchanged): `background: -webkit-linear-gradient(350.5deg, #fff, #000);`
Screenshot 2025-04-11 at 22 36 16


  - After `background: -webkit-linear-gradient(99.5deg, #fff, #000)`
Screenshot 2025-04-11 at 22 37 41

File: src/values/gradient.rs (hunk 2 above)
Comment (yisibl) [reply src/values/gradient.rs:582]: The link here requires the use of “Copy permalink”

image

File: src/lib.rs (hunk 3 above)
Comment (yisibl) [reply src/lib.rs:13045]: Great, more bugs in lightningcss can be fixed with more comprehensive test cases.

File: src/lib.rs [hunk 4]
```diff
@@ -13421,6 +13421,357 @@ mod tests {
         ..Browsers::default()
       },
     );
+
+    // Test cases from https://github.com/postcss/autoprefixer/blob/main/test/cases/gradient.css
```
Comment (yisibl) [inline src/lib.rs:13425]: Please use GitHub's "Copy permalink"

File: src/values/gradient.rs [hunk 5]
```diff
@@ -530,6 +540,52 @@ impl LineDirection {
...
+        Angle::Rad(_) | Angle::Grad(_) | Angle::Turn(_) => LineDirection::Angle(angle),
```
Comment (devongovett) [inline src/values/gradient.rs:583]: Do we need to adjust these angles as well?

**Review by devongovett — APPROVED** [review]

File: src/values/gradient.rs (hunk 5 above)
Comment (lucasweng) [reply src/values/gradient.rs:583]: You're right. I’ll look into fixing the angle conversion for those.

File: src/lib.rs [hunk 6]
```diff
@@ -13421,6 +13421,357 @@ mod tests {
...
+          background: -webkit-linear-gradient(32.704deg, #fff, #000);
+          background: -o-linear-gradient(32.704deg, #fff, #000);
+          background: linear-gradient(57.2958deg, #fff, #000);
+        }
+
+        .turn {
+          background: -webkit-linear-gradient(342deg, #fff, #000);
+          background: -o-linear-gradient(342deg, #fff, #000);
+          background: linear-gradient(.3turn, #fff, #000);
+        }
```
Comment (lucasweng) [inline src/lib.rs:13678]: Angle conversion now handles `grad`, `rad`, and `turn`.

<details>
  <summary><code>background: linear-gradient(1grad, white, black);</code></summary>

  test1

Output `background: -webkit-linear-gradient(89.1deg, #fff, #000);`
out1
</details>

<details>
  <summary>
    <code>background: linear-gradient(1rad, white, black);</code>
  </summary>

  test2


Output `background: -webkit-linear-gradient(32.704deg, #fff, #000);`
out2
</details>


<details>
  <summary>
    <code>background: linear-gradient(0.3turn, white, black);</code>
  </summary>

test3


Output `background: -webkit-linear-gradient(342deg, #fff, #000);`
out3
</details>

**Review by devongovett — APPROVED** [review]
